/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#131314',
        'surface-dim': '#131314',
        'surface-bright': '#3a393a',
        'surface-container-lowest': '#0e0e0f',
        'surface-container-low': '#1c1b1c',
        'surface-container': '#201f20',
        'surface-container-high': '#2a2a2b',
        'surface-container-highest': '#353436',
        'on-surface': '#e5e2e3',
        'on-surface-variant': '#cbc3d7',
        'inverse-surface': '#e5e2e3',
        'inverse-on-surface': '#313031',
        outline: '#958ea0',
        'outline-variant': '#494454',
        'surface-tint': '#8B5CF6',
        primary: '#8B5CF6',
        'on-primary': '#ffffff',
        'primary-container': '#a078ff',
        'on-primary-container': '#340080',
        'inverse-primary': '#6d3bd7',
        secondary: '#06B6D4',
        'on-secondary': '#ffffff',
        'secondary-container': '#03b5d3',
        'on-secondary-container': '#00424e',
        tertiary: '#10B981',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#00a572',
        'on-tertiary-container': '#00311f',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        background: '#0A0A0B',
        'on-background': '#e5e2e3'
      },
      fontFamily: {
        "display-xl": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-xl": ["60px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["36px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "500" }]
      },
      spacing: {
        unit: '4px',
        xs: '0.5rem',
        sm: '1rem',
        md: '1.5rem',
        lg: '2.5rem',
        xl: '4rem',
        gutter: '1.5rem',
        margin: '2rem',
      }
    },
  },
  plugins: [],
}
